# -*- coding: utf-8 -*-
"""Medialuno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGDtbFHJABAXeyzqgYQvdA_IfFJrER83
"""

aluno = input('digite o nome do aluno')
n1 = float(input('informe a primeira nota '))
n2 = float(input('informe a segundo nota'))
n3 = float(input('informe a terceira nota'))
media = (n1+n2+n3)/3
if media >= 7:
    situacao = 'aprovado'
elif media >= 5:
    situacao = 'ficou em recuperação'
else:
    situacao = 'reprovado'
print(f'O aluno {aluno} {situacao} com média {media}')